### ISSUE TITLE
请问这个可以构建在Github Pages上面吗？

### ISSUE THREAD

**Issue by Xuanwo** [xmeng1/daux#2]

**Comment by xmeng1** [comment]
这个需要PHP 解析器,所以不能再 github上构建

**Comment by Xuanwo** [comment]
好的，我明白了，谢谢～

**Comment by xmeng1** [comment]
不客气 你是要生成文档吗?  可以试试 https://readthedocs.org/

**Comment by Xuanwo** [comment]
谢。

------------------ 原始邮件 ------------------
发件人: "xin-meng"notifications@github.com; 
发送时间: 2014年6月10日(星期二) 晚上11:06
收件人: "xin-meng/daux"daux@noreply.github.com; 
抄送: "漩涡"vars.cn@gmail.com; 
主题: Re: [daux] 请问这个可以构建在Github Pages上面吗？ (#2)

不客气 你是要生成文档吗?  可以试试 https://readthedocs.org/ 

&mdash;
